### ISSUE TITLE
Undefined reference to micro-ros functions from imported headers

### ISSUE THREAD

**Issue by aistehoo** [anasderkaoui/ROS2-and-Arduino-serial-communication#1]
![image](https://github.com/anasderkaoui/ROS2-and-Arduino-serial-communication/assets/170063330/9bec7efa-a239-48a0-ac40-9cf489bc742e)

Software:
Arduino 1.8.19
ROS2 Humble
micro-ROS v2.0.5

Hardware:
Arduino due

I've imported the necessary libraries but I cannot build the code as the code is not accessing the functions ("empty" functions"). I followed your steps. What am I missing? I can't be importing the c. files over... that would be too hard and time consuming.

Tried:
1. Patching platform.txt
2. Reinstalling Arduino

**Comment by anasderkaoui** [comment]
Hello, thanks for your message.
I am not so sure about what is causing this issue. Make sure to go to the micro-ros repo and see if the Arduino Due is supported and can run your example (sometimes, using micro-ros examples, a board can run a program but not the one).
I had a similar issue when I tried to upload a micro-ros example to an Arduino UNO and got similar error messages !
I hope this will help you figure out your problem.

**Comment by aistehoo** [comment]
Did you cross-compile where by the micro-ros arduino library is built? 

EDIT:
It was an issue on my end! I patched the wrong txt.
